2023-05-10 07:07:51,012 ERROR: Exception on /contact [GET] [in /Users/khg/.local/share/virtualenvs/personal_webpage-ol-bP6tQ/lib/python3.11/site-packages/flask/app.py:1744]
Traceback (most recent call last):
  File "/Users/khg/.local/share/virtualenvs/personal_webpage-ol-bP6tQ/lib/python3.11/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/khg/.local/share/virtualenvs/personal_webpage-ol-bP6tQ/lib/python3.11/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/khg/.local/share/virtualenvs/personal_webpage-ol-bP6tQ/lib/python3.11/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/khg/.local/share/virtualenvs/personal_webpage-ol-bP6tQ/lib/python3.11/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/khg/LOCAL_Documents/code/current/personal_webpage/app/contact/routes.py", line 20, in contact
    return render_template('email/contact_form.html', title='Sign In', form=form)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/khg/.local/share/virtualenvs/personal_webpage-ol-bP6tQ/lib/python3.11/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/khg/.local/share/virtualenvs/personal_webpage-ol-bP6tQ/lib/python3.11/site-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/khg/.local/share/virtualenvs/personal_webpage-ol-bP6tQ/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/Users/khg/.local/share/virtualenvs/personal_webpage-ol-bP6tQ/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/khg/LOCAL_Documents/code/current/personal_webpage/app/templates/email/contact_form.html", line 1, in top-level template code
    {%  extends 'main.base.html' %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/khg/.local/share/virtualenvs/personal_webpage-ol-bP6tQ/lib/python3.11/site-packages/flask/templating.py", line 62, in get_source
    return self._get_source_fast(environment, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/khg/.local/share/virtualenvs/personal_webpage-ol-bP6tQ/lib/python3.11/site-packages/flask/templating.py", line 98, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: main.base.html
2023-05-10 07:08:06,882 INFO: Microblog startup [in /Users/khg/LOCAL_Documents/code/current/personal_webpage/app/__init__.py:76]
2023-05-10 07:12:14,599 INFO: Microblog startup [in /Users/khg/LOCAL_Documents/code/current/personal_webpage/app/__init__.py:76]
2023-05-10 07:12:37,721 INFO: Microblog startup [in /Users/khg/LOCAL_Documents/code/current/personal_webpage/app/__init__.py:76]
